
CREATE TABLE bp_zamestnanec
(
    id_zamestnanec       INTEGER  NOT NULL ,
    od                   DATE  NOT NULL ,
    do                   DATE  NULL ,
    plat                 INTEGER  NOT NULL ,
    uvazok               CHAR(1)  NOT NULL ,
    pozicia              CHAR(1)  NOT NULL ,
    rod_cislo            CHAR(11)  NOT NULL
);

ALTER TABLE bp_zamestnanec
    ADD CONSTRAINT  XPKbp_zamestnanec PRIMARY KEY (id_zamestnanec);

CREATE TABLE bp_test
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    popis                VARCHAR2(350)  NOT NULL
);

alter table bp_test modify popis NULL;

insert into bp_test (popis)
values ('Alexander');

select *
from bp_test;

ALTER TABLE bp_kategoria
    ADD CONSTRAINT  XPKbp_kategoria PRIMARY KEY (id_kategoria);

CREATE TABLE bp_objednavka
(
    id_objednavka        INTEGER  NOT NULL ,
    cas_objednavky       DATE  NOT NULL ,
    sposob_platby        CHAR(1)  NOT NULL ,
    celkova_cena         INTEGER  NOT NULL ,
    id_pouzivatel        INTEGER  NULL ,
    id_zamestnanec       INTEGER  NOT NULL ,
    sposob_dopravy       CHAR(1)  NOT NULL ,
    vratena              CHAR(1)  NULL
);

ALTER TABLE bp_objednavka
    ADD CONSTRAINT  XPKbp_objednavka PRIMARY KEY (id_objednavka);

CREATE TABLE bp_pouzivatel
(
    id_pouzivatel        INTEGER  NOT NULL ,
    cas_registracie      DATE  NOT NULL ,
    rod_cislo            CHAR(11)  NOT NULL
);

ALTER TABLE bp_pouzivatel
    ADD CONSTRAINT  XPKbp_pouzivatel PRIMARY KEY (id_pouzivatel);

CREATE TABLE bp_produkt
(
    id_produkt           INTEGER  NOT NULL ,
    cena                 INTEGER  NOT NULL ,
    mnozstvo             INTEGER  NOT NULL ,
    popis                VARCHAR2(300)  NOT NULL ,
    nazov                VARCHAR2(50)  NOT NULL ,
    vaha                 INTEGER  NULL ,
    id_kategoria         INTEGER  NOT NULL
);

ALTER TABLE bp_produkt
    ADD CONSTRAINT  XPKbp_produkt PRIMARY KEY (id_produkt);

CREATE TABLE bp_objednavka_produkt
(
    id_produkt           INTEGER  NOT NULL ,
    id_objednavka        INTEGER  NOT NULL ,
    pocet_objednanych_kusov INTEGER  NOT NULL
);

ALTER TABLE bp_objednavka_produkt
    ADD CONSTRAINT  XPKbp_objednavka_produkt PRIMARY KEY (id_produkt,id_objednavka);

ALTER TABLE bp_zamestnanec
    ADD (
        CONSTRAINT BP_2 FOREIGN KEY (rod_cislo) REFERENCES bp_os_udaje (rod_cislo) ON DELETE SET NULL);

ALTER TABLE bp_kategoria
    ADD (
        CONSTRAINT BP_12 FOREIGN KEY (id_zamestnanec) REFERENCES bp_zamestnanec (id_zamestnanec) ON DELETE SET NULL);

ALTER TABLE bp_objednavka
    ADD (
        CONSTRAINT BP_10 FOREIGN KEY (id_pouzivatel) REFERENCES bp_pouzivatel (id_pouzivatel) ON DELETE SET NULL);

ALTER TABLE bp_objednavka
    ADD (
        CONSTRAINT BP_11 FOREIGN KEY (id_zamestnanec) REFERENCES bp_zamestnanec (id_zamestnanec) ON DELETE SET NULL);

ALTER TABLE bp_pouzivatel
    ADD (
        CONSTRAINT BP_1 FOREIGN KEY (rod_cislo) REFERENCES bp_os_udaje (rod_cislo) ON DELETE SET NULL);

ALTER TABLE bp_produkt
    ADD (
        CONSTRAINT BP_9 FOREIGN KEY (id_kategoria) REFERENCES bp_kategoria (id_kategoria) ON DELETE SET NULL);

ALTER TABLE bp_objednavka_produkt
    ADD (
        CONSTRAINT BP_6 FOREIGN KEY (id_produkt) REFERENCES bp_produkt (id_produkt));

ALTER TABLE bp_objednavka_produkt
    ADD (
        CONSTRAINT BP_7 FOREIGN KEY (id_objednavka) REFERENCES bp_objednavka (id_objednavka));

INSERT INTO bp_pouzivatel (id_pouzivatel, rod_cislo, cas_registracie) VALUES
(20, '123456/7809', TO_DATE('2023-01-20', 'YYYY-MM-DD'));

INSERT INTO bp_os_udaje (rod_cislo, meno, priezvisko, tel_cislo, email, psc, ulica, mesto) VALUES
('123456/7809', 'Katarina', 'Flip', '0905123475', 'katarina.flip@example.com', '04005', 'Kosicka 15', 'Kosice');

INSERT INTO bp_zamestnanec (id_zamestnanec, rod_cislo, do, od, plat, uvazok, pozicia) VALUES
(1, '123456/7809', NULL, TO_DATE('2023-07-01', 'YYYY-MM-DD'), 1400, 'A', 'C');

INSERT INTO bp_kategoria (id_kategoria, nazov, popis, id_zamestnanec) VALUES
(20, 'Diely', 'N�hradn� diely pre skateboardy', 1);

INSERT INTO bp_produkt (id_produkt, id_kategoria, nazov, popis, vaha, cena, mnozstvo) VALUES
(20, 10, 'Element Backpack', 'Batoh Element na skateboarding', 0.7, 55, 10);

select *
from bp_zamestnanec;

INSERT INTO bp_kategoria (id_kategoria, nazov, popis, id_zamestnanec) VALUES
(5, 'Ložiská', 'Rýchle ložiská pre hladkú jazdu', 1);

select *
from bp_zamestnanec;

INSERT INTO bp_os_udaje (rod_cislo, meno, priezvisko, tel_cislo, email, psc, ulica, mesto) VALUES
('950530/3456', 'Tomáš', 'Král', '0905123456', 'tomas.kral@example.com', '01001', 'Západná 7', 'Žilina');

INSERT INTO bp_zamestnanec (id_zamestnanec, rod_cislo, od, do, plat, uvazok, pozicia) VALUES
(6, '950530/3456', TO_DATE('2024-04-07', 'YYYY-MM-DD'), NULL, 1650, 'F', 'A');


INSERT INTO bp_produkt (id_produkt, id_kategoria, nazov, popis, vaha, cena, mnozstvo) VALUES
(30, 5, 'Ložiská Pro Fast', 'Rýchle ložiská pre závodnú jazdu', 52, 14, 95);


INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (1, 1, 5, TO_DATE('2024-11-01', 'YYYY-MM-DD'), 'C', 'P', 150, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (2, 2, 3, TO_DATE('2024-11-02', 'YYYY-MM-DD'), 'K', 'B', 230, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (3, 4, 1, TO_DATE('2024-11-03', 'YYYY-MM-DD'), 'P', 'A', 120, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (4, 3, 12, TO_DATE('2024-11-04', 'YYYY-MM-DD'), 'C', 'P', 340, 'A');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (5, 1, 7, TO_DATE('2024-11-05', 'YYYY-MM-DD'), 'P', 'A', 270, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (6, 2, 10, TO_DATE('2024-11-06', 'YYYY-MM-DD'), 'K', 'P', 180, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (7, 3, 15, TO_DATE('2024-11-07', 'YYYY-MM-DD'), 'C', 'B', 250, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (8, 4, 8, TO_DATE('2024-11-08', 'YYYY-MM-DD'), 'P', 'A', 300, 'A');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (9, 1, 4, TO_DATE('2024-11-09', 'YYYY-MM-DD'), 'C', 'P', 200, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (10, 2, 11, TO_DATE('2024-11-10', 'YYYY-MM-DD'), 'K', 'B', 275, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (11, 3, 6, TO_DATE('2024-11-11', 'YYYY-MM-DD'), 'P', 'A', 320, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (12, 4, 13, TO_DATE('2024-11-12', 'YYYY-MM-DD'), 'C', 'P', 290, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (13, 1, 9, TO_DATE('2024-11-13', 'YYYY-MM-DD'), 'K', 'B', 310, 'A');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (14, 2, 17, TO_DATE('2024-11-14', 'YYYY-MM-DD'), 'P', 'A', 350, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (15, 3, 2, TO_DATE('2024-11-15', 'YYYY-MM-DD'), 'C', 'P', 180, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (16, 4, 19, TO_DATE('2024-11-16', 'YYYY-MM-DD'), 'K', 'B', 265, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (17, 1, 16, TO_DATE('2024-11-17', 'YYYY-MM-DD'), 'P', 'A', 220, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (18, 2, 18, TO_DATE('2024-11-18', 'YYYY-MM-DD'), 'C', 'P', 330, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (19, 3, 14, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'K', 'B', 295, 'N');
INSERT INTO bp_objednavka (id_objednavka, id_zamestnanec, id_pouzivatel, cas_objednavky, sposob_platby, sposob_dopravy, celkova_cena, vratena) VALUES (20, 4, 20, TO_DATE('2024-11-20', 'YYYY-MM-DD'), 'P', 'A', 310, 'N');

select *
from bp_objednavka;

ALTER TABLE bp_objednavka_produkt
    ADD realna_cena integer;

select *
from bp_objednavka_produkt;

INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (1, 1, 95, 1);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (2, 1, 55, 1);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (3, 2, 70, 2);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (5, 3, 16, 3);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (7, 4, 35, 4);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (9, 5, 9, 5);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (4, 6, 36, 2);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (6, 7, 21, 4);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (8, 8, 45, 2);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (10, 9, 14, 7);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (11, 10, 100, 1);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (12, 11, 85, 3);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (13, 12, 27, 2);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (14, 13, 59, 4);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (15, 14, 7, 6);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (16, 15, 20, 5);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (17, 16, 103, 1);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (18, 17, 83, 2);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (19, 18, 11, 8);
INSERT INTO bp_objednavka_produkt (id_produkt, id_objednavka, realna_cena, pocet_objednanych_kusov) VALUES (20, 19, 67, 3);


select * from bp_produkt;

select * from BP_PRODUKT;

select *
from bp_objednavka obj
    join bp_pouzivatel bp on obj.id_pouzivatel = bp.id_pouzivatel
        join BP_OS_UDAJE os on bp.ROD_CISLO = os.ROD_CISLO;

delete from bp_produkt where id_produkt = 70;

SELECT o.ID_OBJEDNAVKA, o.CAS_OBJEDNAVKY, o.CELKOVA_CENA,
        o.SPOSOB_PLATBY, o.SPOSOB_DOPRAVY, o.VRATENA, o.ID_POUZIVATEL
 FROM BP_OBJEDNAVKA o
 WHERE o.ID_OBJEDNAVKA = :orderId;

SELECT ID_POUZIVATEL FROM BP_POUZIVATEL WHERE ROD_CISLO = (
    SELECT ROD_CISLO FROM BP_OS_UDAJE WHERE EMAIL = :email
)

select *
from bp_adresy;


select *
from P_MESTO;








